name: Check correct formatting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Use Node.js 20
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: 20.19.6
          cache: "npm"
      - run: npm ci
      - run: npm run format --if-present
      - name: Verify files didn't change
        uses: tj-actions/verify-changed-files@a1c6acee9df209257a246f2cc6ae8cb6581c1edf # v20
        with:
          fail-if-changed: "true"
